### ISSUE TITLE
Bug Moving from older versions of SS to new SS

### ISSUE THREAD

**Issue by garet90** [garet90/simple-skyblock#33]
16.01 19:56:06 [Server] ERROR Could not pass event BlockFromToEvent to SimpleSkyblock v1.3.5
16.01 19:56:06 [Server] INFO java.lang.NullPointerException: null
16.01 19:56:06 [Server] INFO at holiday.garet.skyblock.island.Island.hasPlayer(Island.java:143) ~[?:?]
16.01 19:56:06 [Server] INFO at holiday.garet.skyblock.SimpleSkyblock.getPlayerIsland(SimpleSkyblock.java:1929) ~[?:?]
16.01 19:56:06 [Server] INFO at holiday.garet.skyblock.SimpleSkyblock.onFromTo(SimpleSkyblock.java:1427) ~[?:?]
16.01 19:56:06 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source) ~[?:?]
16.01 19:56:06 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:188) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:508) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.Fluid.a(SourceFile:70) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:667) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:389) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
16.01 19:56:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by garet90** [comment]
Fixed in next update
